version: '2'

services:

  web:
    container_name: asteria-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8082:8080'

